url: "https://wagnerrosa.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Wagner Rosa" # the name of your site, e.g. ACME Corp.
description: "Wagner Rosa enjoy in making things for human people. I am living at Porto Alegre and working with video editing, web and graphic design."

#sass output
sass:
  style: compressed
